# Generated by Django 2.1 on 2018-08-30 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=255, verbose_name='userId')),
            ],
        ),
        migrations.CreateModel(
            name='ClickerItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Status New'), (1, 'Status Ongoing'), (2, 'Status Completed')], default=2, verbose_name='status')),
                ('body', models.TextField(verbose_name='Body')),
                ('resourceLinkId', models.TextField(verbose_name='ResourceLinkId')),
            ],
        ),
        migrations.CreateModel(
            name='ClickerOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Title')),
                ('clickerItem', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='clickerOptions', to='clickercore.ClickerItem')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='clickerItem',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='clickercore.ClickerItem'),
        ),
        migrations.AddField(
            model_name='answer',
            name='clickerOption',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='clickercore.ClickerOption'),
        ),
    ]
